# Generated by Django 6.1 on 2026-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, help_text='Leave blank to use your profile CV', null=True, upload_to='application_cvs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, help_text='Leave blank to use your profile name', max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Leave blank to use your profile phone number', max_length=20),
        ),
    ]
