# Generated by Django 6.0.7 on 2026-07-28 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship'), ('VOLUNTEER', 'Volunteer')], default='INTERNSHIP', max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('duration_weeks', models.PositiveIntegerField(help_text='Duration in weeks')),
                ('skills_required', models.CharField(blank=True, help_text='Comma-separated, e.g. Python, Django, Communication', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'EMPLOYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
    ]
